# Generated by Django 6.1.1 on 2026-09-18 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
