# Generated by Django 6.1.1 on 2026-09-11 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
